/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class wbc_test_data_t implements lcm.lcm.LCMEncodable
{
    public int contact_est[];
    public float fr_Fr_des[];
    public float fl_Fr_des[];
    public float hr_Fr_des[];
    public float hl_Fr_des[];
    public float fr_Fr[];
    public float fl_Fr[];
    public float hr_Fr[];
    public float hl_Fr[];
    public float body_ori[];
    public float body_ang_vel[];
    public float fr_foot_pos_cmd[];
    public float fl_foot_pos_cmd[];
    public float hr_foot_pos_cmd[];
    public float hl_foot_pos_cmd[];
    public float fr_foot_vel_cmd[];
    public float fl_foot_vel_cmd[];
    public float hr_foot_vel_cmd[];
    public float hl_foot_vel_cmd[];
    public float fr_foot_local_pos[];
    public float fl_foot_local_pos[];
    public float hr_foot_local_pos[];
    public float hl_foot_local_pos[];
    public float fr_foot_local_vel[];
    public float fl_foot_local_vel[];
    public float hr_foot_local_vel[];
    public float hl_foot_local_vel[];
    public float jpos_cmd[];
    public float jvel_cmd[];
    public float jacc_cmd[];
    public float vision_loc[];
 
    public wbc_test_data_t()
    {
        contact_est = new int[2];
        fr_Fr_des = new float[3];
        fl_Fr_des = new float[3];
        hr_Fr_des = new float[3];
        hl_Fr_des = new float[3];
        fr_Fr = new float[3];
        fl_Fr = new float[3];
        hr_Fr = new float[3];
        hl_Fr = new float[3];
        body_ori = new float[4];
        body_ang_vel = new float[4];
        fr_foot_pos_cmd = new float[3];
        fl_foot_pos_cmd = new float[3];
        hr_foot_pos_cmd = new float[3];
        hl_foot_pos_cmd = new float[3];
        fr_foot_vel_cmd = new float[3];
        fl_foot_vel_cmd = new float[3];
        hr_foot_vel_cmd = new float[3];
        hl_foot_vel_cmd = new float[3];
        fr_foot_local_pos = new float[3];
        fl_foot_local_pos = new float[3];
        hr_foot_local_pos = new float[3];
        hl_foot_local_pos = new float[3];
        fr_foot_local_vel = new float[3];
        fl_foot_local_vel = new float[3];
        hr_foot_local_vel = new float[3];
        hl_foot_local_vel = new float[3];
        jpos_cmd = new float[12];
        jvel_cmd = new float[12];
        jacc_cmd = new float[12];
        vision_loc = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xa8714a107050fbdbL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.wbc_test_data_t.class))
            return 0L;
 
        classes.add(lcmtypes.wbc_test_data_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 2; a++) {
            outs.writeInt(this.contact_est[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.fr_Fr_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.fl_Fr_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hr_Fr_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hl_Fr_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.fr_Fr[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.fl_Fr[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hr_Fr[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hl_Fr[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.body_ori[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.body_ang_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.fr_foot_pos_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.fl_foot_pos_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hr_foot_pos_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hl_foot_pos_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.fr_foot_vel_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.fl_foot_vel_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hr_foot_vel_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hl_foot_vel_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.fr_foot_local_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.fl_foot_local_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hr_foot_local_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hl_foot_local_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.fr_foot_local_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.fl_foot_local_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hr_foot_local_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hl_foot_local_vel[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.jpos_cmd[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.jvel_cmd[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.jacc_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.vision_loc[a]); 
        }
 
    }
 
    public wbc_test_data_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public wbc_test_data_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.wbc_test_data_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.wbc_test_data_t o = new lcmtypes.wbc_test_data_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.contact_est = new int[(int) 2];
        for (int a = 0; a < 2; a++) {
            this.contact_est[a] = ins.readInt();
        }
 
        this.fr_Fr_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.fr_Fr_des[a] = ins.readFloat();
        }
 
        this.fl_Fr_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.fl_Fr_des[a] = ins.readFloat();
        }
 
        this.hr_Fr_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hr_Fr_des[a] = ins.readFloat();
        }
 
        this.hl_Fr_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hl_Fr_des[a] = ins.readFloat();
        }
 
        this.fr_Fr = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.fr_Fr[a] = ins.readFloat();
        }
 
        this.fl_Fr = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.fl_Fr[a] = ins.readFloat();
        }
 
        this.hr_Fr = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hr_Fr[a] = ins.readFloat();
        }
 
        this.hl_Fr = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hl_Fr[a] = ins.readFloat();
        }
 
        this.body_ori = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.body_ori[a] = ins.readFloat();
        }
 
        this.body_ang_vel = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.body_ang_vel[a] = ins.readFloat();
        }
 
        this.fr_foot_pos_cmd = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.fr_foot_pos_cmd[a] = ins.readFloat();
        }
 
        this.fl_foot_pos_cmd = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.fl_foot_pos_cmd[a] = ins.readFloat();
        }
 
        this.hr_foot_pos_cmd = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hr_foot_pos_cmd[a] = ins.readFloat();
        }
 
        this.hl_foot_pos_cmd = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hl_foot_pos_cmd[a] = ins.readFloat();
        }
 
        this.fr_foot_vel_cmd = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.fr_foot_vel_cmd[a] = ins.readFloat();
        }
 
        this.fl_foot_vel_cmd = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.fl_foot_vel_cmd[a] = ins.readFloat();
        }
 
        this.hr_foot_vel_cmd = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hr_foot_vel_cmd[a] = ins.readFloat();
        }
 
        this.hl_foot_vel_cmd = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hl_foot_vel_cmd[a] = ins.readFloat();
        }
 
        this.fr_foot_local_pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.fr_foot_local_pos[a] = ins.readFloat();
        }
 
        this.fl_foot_local_pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.fl_foot_local_pos[a] = ins.readFloat();
        }
 
        this.hr_foot_local_pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hr_foot_local_pos[a] = ins.readFloat();
        }
 
        this.hl_foot_local_pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hl_foot_local_pos[a] = ins.readFloat();
        }
 
        this.fr_foot_local_vel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.fr_foot_local_vel[a] = ins.readFloat();
        }
 
        this.fl_foot_local_vel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.fl_foot_local_vel[a] = ins.readFloat();
        }
 
        this.hr_foot_local_vel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hr_foot_local_vel[a] = ins.readFloat();
        }
 
        this.hl_foot_local_vel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hl_foot_local_vel[a] = ins.readFloat();
        }
 
        this.jpos_cmd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.jpos_cmd[a] = ins.readFloat();
        }
 
        this.jvel_cmd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.jvel_cmd[a] = ins.readFloat();
        }
 
        this.jacc_cmd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.jacc_cmd[a] = ins.readFloat();
        }
 
        this.vision_loc = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.vision_loc[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.wbc_test_data_t copy()
    {
        lcmtypes.wbc_test_data_t outobj = new lcmtypes.wbc_test_data_t();
        outobj.contact_est = new int[(int) 2];
        System.arraycopy(this.contact_est, 0, outobj.contact_est, 0, 2); 
        outobj.fr_Fr_des = new float[(int) 3];
        System.arraycopy(this.fr_Fr_des, 0, outobj.fr_Fr_des, 0, 3); 
        outobj.fl_Fr_des = new float[(int) 3];
        System.arraycopy(this.fl_Fr_des, 0, outobj.fl_Fr_des, 0, 3); 
        outobj.hr_Fr_des = new float[(int) 3];
        System.arraycopy(this.hr_Fr_des, 0, outobj.hr_Fr_des, 0, 3); 
        outobj.hl_Fr_des = new float[(int) 3];
        System.arraycopy(this.hl_Fr_des, 0, outobj.hl_Fr_des, 0, 3); 
        outobj.fr_Fr = new float[(int) 3];
        System.arraycopy(this.fr_Fr, 0, outobj.fr_Fr, 0, 3); 
        outobj.fl_Fr = new float[(int) 3];
        System.arraycopy(this.fl_Fr, 0, outobj.fl_Fr, 0, 3); 
        outobj.hr_Fr = new float[(int) 3];
        System.arraycopy(this.hr_Fr, 0, outobj.hr_Fr, 0, 3); 
        outobj.hl_Fr = new float[(int) 3];
        System.arraycopy(this.hl_Fr, 0, outobj.hl_Fr, 0, 3); 
        outobj.body_ori = new float[(int) 4];
        System.arraycopy(this.body_ori, 0, outobj.body_ori, 0, 4); 
        outobj.body_ang_vel = new float[(int) 4];
        System.arraycopy(this.body_ang_vel, 0, outobj.body_ang_vel, 0, 4); 
        outobj.fr_foot_pos_cmd = new float[(int) 3];
        System.arraycopy(this.fr_foot_pos_cmd, 0, outobj.fr_foot_pos_cmd, 0, 3); 
        outobj.fl_foot_pos_cmd = new float[(int) 3];
        System.arraycopy(this.fl_foot_pos_cmd, 0, outobj.fl_foot_pos_cmd, 0, 3); 
        outobj.hr_foot_pos_cmd = new float[(int) 3];
        System.arraycopy(this.hr_foot_pos_cmd, 0, outobj.hr_foot_pos_cmd, 0, 3); 
        outobj.hl_foot_pos_cmd = new float[(int) 3];
        System.arraycopy(this.hl_foot_pos_cmd, 0, outobj.hl_foot_pos_cmd, 0, 3); 
        outobj.fr_foot_vel_cmd = new float[(int) 3];
        System.arraycopy(this.fr_foot_vel_cmd, 0, outobj.fr_foot_vel_cmd, 0, 3); 
        outobj.fl_foot_vel_cmd = new float[(int) 3];
        System.arraycopy(this.fl_foot_vel_cmd, 0, outobj.fl_foot_vel_cmd, 0, 3); 
        outobj.hr_foot_vel_cmd = new float[(int) 3];
        System.arraycopy(this.hr_foot_vel_cmd, 0, outobj.hr_foot_vel_cmd, 0, 3); 
        outobj.hl_foot_vel_cmd = new float[(int) 3];
        System.arraycopy(this.hl_foot_vel_cmd, 0, outobj.hl_foot_vel_cmd, 0, 3); 
        outobj.fr_foot_local_pos = new float[(int) 3];
        System.arraycopy(this.fr_foot_local_pos, 0, outobj.fr_foot_local_pos, 0, 3); 
        outobj.fl_foot_local_pos = new float[(int) 3];
        System.arraycopy(this.fl_foot_local_pos, 0, outobj.fl_foot_local_pos, 0, 3); 
        outobj.hr_foot_local_pos = new float[(int) 3];
        System.arraycopy(this.hr_foot_local_pos, 0, outobj.hr_foot_local_pos, 0, 3); 
        outobj.hl_foot_local_pos = new float[(int) 3];
        System.arraycopy(this.hl_foot_local_pos, 0, outobj.hl_foot_local_pos, 0, 3); 
        outobj.fr_foot_local_vel = new float[(int) 3];
        System.arraycopy(this.fr_foot_local_vel, 0, outobj.fr_foot_local_vel, 0, 3); 
        outobj.fl_foot_local_vel = new float[(int) 3];
        System.arraycopy(this.fl_foot_local_vel, 0, outobj.fl_foot_local_vel, 0, 3); 
        outobj.hr_foot_local_vel = new float[(int) 3];
        System.arraycopy(this.hr_foot_local_vel, 0, outobj.hr_foot_local_vel, 0, 3); 
        outobj.hl_foot_local_vel = new float[(int) 3];
        System.arraycopy(this.hl_foot_local_vel, 0, outobj.hl_foot_local_vel, 0, 3); 
        outobj.jpos_cmd = new float[(int) 12];
        System.arraycopy(this.jpos_cmd, 0, outobj.jpos_cmd, 0, 12); 
        outobj.jvel_cmd = new float[(int) 12];
        System.arraycopy(this.jvel_cmd, 0, outobj.jvel_cmd, 0, 12); 
        outobj.jacc_cmd = new float[(int) 12];
        System.arraycopy(this.jacc_cmd, 0, outobj.jacc_cmd, 0, 12); 
        outobj.vision_loc = new float[(int) 3];
        System.arraycopy(this.vision_loc, 0, outobj.vision_loc, 0, 3); 
        return outobj;
    }
 
}

