/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class xyzq_pose_t implements lcm.lcm.LCMEncodable
{
    public double xyz[];
    public double wxyz_quaternion[];
 
    public xyzq_pose_t()
    {
        xyz = new double[3];
        wxyz_quaternion = new double[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0dad6ea432bb46e3L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.xyzq_pose_t.class))
            return 0L;
 
        classes.add(lcmtypes.xyzq_pose_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.xyz[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeDouble(this.wxyz_quaternion[a]); 
        }
 
    }
 
    public xyzq_pose_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public xyzq_pose_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.xyzq_pose_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.xyzq_pose_t o = new lcmtypes.xyzq_pose_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.xyz = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.xyz[a] = ins.readDouble();
        }
 
        this.wxyz_quaternion = new double[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.wxyz_quaternion[a] = ins.readDouble();
        }
 
    }
 
    public lcmtypes.xyzq_pose_t copy()
    {
        lcmtypes.xyzq_pose_t outobj = new lcmtypes.xyzq_pose_t();
        outobj.xyz = new double[(int) 3];
        System.arraycopy(this.xyz, 0, outobj.xyz, 0, 3); 
        outobj.wxyz_quaternion = new double[(int) 4];
        System.arraycopy(this.wxyz_quaternion, 0, outobj.wxyz_quaternion, 0, 4); 
        return outobj;
    }
 
}

